# Generated by Django 4.2.5 on 2023-10-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status_of_product',
            field=models.BooleanField(default=False, verbose_name='опубликовано'),
        ),
    ]
