# Generated by Django 4.2.5 on 2023-10-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_status_of_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_status_of_product', 'Can status product')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
