# Generated by Django 4.2.5 on 2023-10-22 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_status_of_product', 'Can status_of_product'), ('set_description', 'Can description'), ('set_category_product', 'Can category_product')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
